/*Consulta 7*/

SELECT EVENTO.ID_EVENTO, FORMA_PAGAMENTO, SUM(PRECO) AS VALOR FROM EVENTO 
JOIN TIPO_INGRESSO ON EVENTO.ID_EVENTO = TIPO_INGRESSO.ID_EVENTO
JOIN INGRESSO ON INGRESSO.ID_EVENTO = TIPO_INGRESSO.ID_EVENTO AND INGRESSO.TIPO_INGRESSO = TIPO_INGRESSO.TIPO
WHERE ORGANIZADOR = 'tgamer'
GROUP BY EVENTO.ID_EVENTO, FORMA_PAGAMENTO;

/*Consulta 9*/
SELECT DISTINCT NOME_LOGIN, CPF, NOME FROM USUARIO
JOIN ALUGUEL ON USUARIO.NOME_LOGIN = ALUGUEL.LOCATARIO OR USUARIO.NOME_LOGIN = ALUGUEL.INSTRUMENTO_DONO
WHERE ALUGUEL.DATA_EMPRESTIMO < '06/04/19' AND '06/04/19' < DATA_DEVOLUCAO; 

/*Consulta 1*/ 
SELECT PROFESSOR, COUNT(*) FROM INSTRUMENTOS_TOCADOS 
JOIN ( SELECT TIPO FROM CLASSIFICACAO_INSTRUMENTO WHERE CLASSIFICACAO = 'DIGITAL') TIPO_INST_CLAS 
ON TIPO_INST_CLAS.TIPO = INSTRUMENTOS_TOCADOS.TIPO_INSTRUMENTO
GROUP BY PROFESSOR
HAVING COUNT(*) = (SELECT COUNT(*) FROM CLASSIFICACAO_INSTRUMENTO WHERE CLASSIFICACAO = 'DIGITAL');

/*Consulta 3 - a que fizemos juntos
Buscar os proprietarios e professores que nunca foram denunciados
*/
SELECT USUARIO_NAO_DEN.USUARIO AS USUARIO FROM ((SELECT NOME_LOGIN AS USUARIO FROM USUARIO)
MINUS (SELECT DENUNCIADO AS USUARIO FROM DENUNCIA)) USUARIO_NAO_DEN
JOIN ((SELECT USUARIO AS USUARIO FROM PROFESSOR)
UNION (SELECT USUARIO AS USUARIO FROM PROPRIETARIO)) PROF_OU_PROP ON USUARIO_NAO_DEN.USUARIO = PROF_OU_PROP.USUARIO;
